name: Run Tests
on :
  push:
    branches:
      main
jobs:
  RunTests:
    runs-on : ubuntu-latest
    steps :
    - name : checkout repositiry
      uses: actions/checkout@v4.2.2

    - name : list repo
      run : ls -la 
      
    - name: run tests
      run : pytest -vs
      
